sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"

install:
    - pip install tox
    - pip install coveralls

script:
    - tox -e py
after_success:
    - coveralls
